#!/usr/bin/python3
from sys import argv
with open(argv[1]) as f:
    for line in f:
        num = int(line)
        print("{:d}=".format(num) , end='')
        if num % 2 == 0:
            print("{}*2".format(num//2))
            continue
        for t in range (3, num, 2):
            if num % t ==0:
                factor = num//t
            for v in range (3, num, 2):
                if factor % v == 0 or v == 0:
                    break
                print("{} * {}".format(factor, t))
                break
